version: '3.3'

services:
  api: 
    build: .
    command: >
      sh -c "npm install &&
      npx nodemon app.ts"
    network_mode: host # TODO: Review how to connect node to mongo without network host
    restart: unless-stopped
    depends_on:
      - db
  db:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    network_mode: host
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: example
      MYSQL_USER: example
      MYSQL_PASSWORD: example
      MYSQL_ROOT_HOST: "%"
    security_opt:
      - seccomp:unconfined
